### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by jsuchal** [fairplaysk/datacamp#10]
- [x] Rozbehat testy 
- [x] https://travis-ci.org
- [x] Pokryt usecasy testami aspon aby sme vedeli ci to nepada.

**Comment by mirrec** [comment]
@jsuchal aktualny vystup z testov

* cucumber
  * pada features/manage_datasets.feature
  * 18 scenarios (6 failed, 12 passed)
  * 70 steps (6 failed, 9 skipped, 55 passed)
* rspec
  * 3066 examples, 0 failures

**Comment by jsuchal** [comment]
@mirrec no neni tak strasne.

@proksik kvoli travis CI bude treba dat mna alebo @mirrec do organizacie. Inak to v Travise neviem pridat. Tak isto code climate + gemnasium.

**Comment by jsuchal** [comment]
Tak CodeClimate ide. https://codeclimate.com/github/fairplaysk/datacamp

**Comment by mirrec** [comment]
@jsuchal high level testy ideme pisat v rspec alebo cucumber? osobne preferujem rspec
ak by sa islo do rspec only, prepisat cucumber testy do rspecu ?

**Comment by jsuchal** [comment]
Podla mna je cucumber zbytocna abstrakcia. Cize dajme rspec.

**Comment by mirrec** [comment]
@jsuchal testy su uz zelene, postupne doplnam a prepisujem testy z cucumberu. zatial to ide trochu pomaly lebo sa zorientovavam v aplikacii.

wip je zatial tu https://github.com/fairplaysk/datacamp/pull/18

**Comment by mirrec** [comment]
@proksik pridal si mna a @jsuchal do organizacie ? lebo s tym travis CI sa nevieme dalej pohnut.

**Comment by jsuchal** [comment]
Do mastra som pridal badges. Vidiet to tu. https://github.com/fairplaysk/datacamp#datacamp

**Comment by mirrec** [comment]
@jsuchal travis ci som rozbehal. dal som to cele do pull requestu https://github.com/fairplaysk/datacamp/pull/20

**Comment by mirrec** [comment]
@jsuchal zatvaram, poriesene v https://github.com/fairplaysk/datacamp/pull/18
