### ISSUE TITLE
Vyhodit sequel z jadra

### ISSUE THREAD

**Issue by jsuchal** [fairplaysk/datacamp#9]
https://github.com/fairplaysk/datacamp/blob/master/lib/datastore_manager.rb

**Comment by jsuchal** [comment]
@mirrec Prva vec je uplne odstranit ten sequel. Refactor jadra s tym suvisi, ale toto je zaciatok. Spravim novu issue na to jadro.

**Comment by mirrec** [comment]
riesene v  https://github.com/fairplaysk/datacamp/pull/34
